language: java
before_install:
  # download the latest android sdk and unzip
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
  - tar xzf android-sdk_r23.0.2-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --filter platform-tools,build-tools-19.1.0,android-21 --no-ui --force --all
install: "mvn install -DskipTests -e -X"
before_script: "mvn android:lint --projects library"
script: "mvn install"
after_failure: cat library/target/lint-results/lint-results.xml || true
